defaults:
  - dataset: wikipedia
  - model: tgn
  - negative_sampling: random
  - optional labeling: null
  - _self_

experiment_name: "m:tgn-nl:random-ds:wikipedia"
seed: 42
device: cpu

training:
  epochs: 50
  lr: 0.0001
  weight_decay: 1e-5
  early_stopping:
    patience: 7

eval:
  eval_every: 1

tensorboard:
  enabled: true
  log_model: true
  log_weights: true

hydra:
  run:
    dir: runs/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: runs/${experiment_name}
    subdir: ${now:%Y-%m-%d_%H-%M-%S}_${hydra.job.num}
